Avoid regex problem on Windows
Don't include the directory path in the regex, because a pattern
starting with "C:\\Users" will result in:

re.error: incomplete escape \U at position 2

Instead, only do the regex on the filename part.